# Generated by Django 4.2.20 on 2025-03-19 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0006_profile_city_profile_country_profile_full_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=10)),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'OTP Record',
                'verbose_name_plural': 'OTP Records',
                'ordering': ['-created_at'],
            },
        ),
    ]
